### ISSUE TITLE
CMVS

### ISSUE THREAD

**Issue by imKota** [MZSHproject/trash#1]
CMVS Hook usage?
For **Aoi Tori** and **Amatsutsumi**

**Comment by MZSHproject** [comment]
Useless code. I have new way to translate.
for Amatsutsumi, see https://github.com/xmoeproject/CMVS-Engine/tree/master/PatchSample/amatsu_trial_chs

**Comment by imKota** [comment]
@MZSHproject But..
https://github.com/xmoeproject/CMVS-Engine/issues/3

**Comment by imKota** [comment]
@MZSHproject do you have discord/telegram?

**Comment by imKota** [comment]
@MZSHproject go to telegram ^~^
